// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sog8262LcebSfK4tonEqFh
// Component: 7EPh6ElWir
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_aker_academy.module.css"; // plasmic-import: sog8262LcebSfK4tonEqFh/projectcss
import sty from "./PlasmicBackLink.module.css"; // plasmic-import: 7EPh6ElWir/css

import BackArrowIcon from "./icons/PlasmicIcon__BackArrow"; // plasmic-import: 3XRP6YsMa/icon

export type PlasmicBackLink__VariantMembers = {
  whiteColour: "whiteColour";
};

export type PlasmicBackLink__VariantsArgs = {
  whiteColour?: SingleBooleanChoiceArg<"whiteColour">;
};

type VariantPropType = keyof PlasmicBackLink__VariantsArgs;
export const PlasmicBackLink__VariantProps = new Array<VariantPropType>(
  "whiteColour"
);

export type PlasmicBackLink__ArgsType = {
  arrowBack?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBackLink__ArgsType;
export const PlasmicBackLink__ArgProps = new Array<ArgPropType>("arrowBack");

export type PlasmicBackLink__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBackLinkProps {
  arrowBack?: React.ReactNode;
  whiteColour?: SingleBooleanChoiceArg<"whiteColour">;
  className?: string;
}

function PlasmicBackLink__RenderFunc(props: {
  variants: PlasmicBackLink__VariantsArgs;
  args: PlasmicBackLink__ArgsType;
  overrides: PlasmicBackLink__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root,
          {
            [sty.rootwhiteColour]: hasVariant(
              variants,
              "whiteColour",
              "whiteColour"
            )
          }
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <BackArrowIcon
              className={classNames(projectcss.all, sty.svg__hw5Gm)}
              role={"img"}
            />
          ),

          value: args.arrowBack,
          className: classNames(sty.slotTargetArrowBack)
        })}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBackLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBackLink__VariantsArgs;
    args?: PlasmicBackLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBackLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBackLink__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBackLink__ArgProps,
      internalVariantPropNames: PlasmicBackLink__VariantProps
    });

    return PlasmicBackLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBackLink";
  } else {
    func.displayName = `PlasmicBackLink.${nodeName}`;
  }
  return func;
}

export const PlasmicBackLink = Object.assign(
  // Top-level PlasmicBackLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBackLink
    internalVariantProps: PlasmicBackLink__VariantProps,
    internalArgProps: PlasmicBackLink__ArgProps
  }
);

export default PlasmicBackLink;
/* prettier-ignore-end */
