// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sog8262LcebSfK4tonEqFh
// Component: 2KszG0-KPy
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_aker_academy.module.css"; // plasmic-import: sog8262LcebSfK4tonEqFh/projectcss
import sty from "./PlasmicButtonOutlined.module.css"; // plasmic-import: 2KszG0-KPy/css

export type PlasmicButtonOutlined__VariantMembers = {};

export type PlasmicButtonOutlined__VariantsArgs = {};
type VariantPropType = keyof PlasmicButtonOutlined__VariantsArgs;
export const PlasmicButtonOutlined__VariantProps = new Array<VariantPropType>();

export type PlasmicButtonOutlined__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicButtonOutlined__ArgsType;
export const PlasmicButtonOutlined__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicButtonOutlined__OverridesType = {
  root?: p.Flex<"button">;
};

export interface DefaultButtonOutlinedProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicButtonOutlined__RenderFunc(props: {
  variants: PlasmicButtonOutlined__VariantsArgs;
  args: PlasmicButtonOutlined__ArgsType;
  overrides: PlasmicButtonOutlined__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Click me",
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonOutlined__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonOutlined__VariantsArgs;
    args?: PlasmicButtonOutlined__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonOutlined__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButtonOutlined__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButtonOutlined__ArgProps,
      internalVariantPropNames: PlasmicButtonOutlined__VariantProps
    });

    return PlasmicButtonOutlined__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButtonOutlined";
  } else {
    func.displayName = `PlasmicButtonOutlined.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonOutlined = Object.assign(
  // Top-level PlasmicButtonOutlined renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicButtonOutlined
    internalVariantProps: PlasmicButtonOutlined__VariantProps,
    internalArgProps: PlasmicButtonOutlined__ArgProps
  }
);

export default PlasmicButtonOutlined;
/* prettier-ignore-end */
