// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { ScreenVariantProvider } from "../components/plasmic/aker_academy/PlasmicGlobalVariant__Screen";
import { PlasmicStep3Project1LampStackImplementation } from "../components/plasmic/aker_academy/PlasmicStep3Project1LampStackImplementation";

function Step3Project1LampStackImplementation() {
  // Use PlasmicStep3Project1LampStackImplementation to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicStep3Project1LampStackImplementation are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicStep3Project1LampStackImplementation is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return <PlasmicStep3Project1LampStackImplementation />;
}

export default Step3Project1LampStackImplementation;
